app/urls.py
from django.urls import path
from .views import CheckCustomerExists, check_for_update, DeviceID, TrialStatus, TrialRequestView

app_name = "app"

urlpatterns = [
    path('check_customer_exists/', CheckCustomerExists.as_view(),
         name="check_customer_exists"),
    path('check_for_update/', check_for_update, name="check_for_update"),
    path('device_id/', DeviceID.as_view(), name="device_id"),
    path('trial_status/', TrialStatus.as_view(), name="device_id"),
    path('trial_request/', TrialRequestView.as_view(), name="trial_request"),
]

butopia/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('adminshowkhunbi/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("app/", include("app.urls", namespace="app")),
    path("phone/", include("phone.urls", namespace="phone")),
    path('accounts/', include('allauth.urls')),
]


handler404 = "core.views.handler404"
handler500 = "core.views.handler500"
handler400 = "core.views.handler400"
handler403 = "core.views.handler403"

core/urls.py
from django.urls import path
from .views import HomeView, PaymentView, verify_transaction, PromoterProfileView, PromoterDashboardView, ReferredView, referrer_payment_view, CashoutView, PortfolioView, ContactView, download


app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name="homeview"),
    path('portfolio/', PortfolioView.as_view(), name="portfolio"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('payment/', PaymentView.as_view(), name="paymentview"),
    path('payment/<slug>/', referrer_payment_view, name="referrerPaymentView"),
    path('verify_transaction/', verify_transaction, name="verify"),
    path('accounts/profile/', PromoterProfileView.as_view(), name="profile"),
    path('accounts/dashboard/', PromoterDashboardView.as_view(), name="dashboard"),
    path('promoter/', PromoterDashboardView.as_view(), name="promoter"),
    path('accounts/referred/', ReferredView.as_view(), name="referred"),
    path('accounts/cashout/', CashoutView.as_view(), name="cashout"),
    path('download/', download, name="download"),
]

templates/Error403.html
<!DOCTYPE html>
<html lang="en"> -->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Butopia 403</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<style>
		* {
			-webkit-box-sizing: border-box;
			box-sizing: border-box;
		}

		body {
			padding: 0;
			margin: 0;
		}

		#notfound {
			position: relative;
			height: 100vh;
		}

		#notfound .notfound {
			position: absolute;
			left: 50%;
			top: 50%;
			-webkit-transform: translate(-50%, -50%);
			-ms-transform: translate(-50%, -50%);
			transform: translate(-50%, -50%);
		}

		.notfound {
			max-width: 560px;
			width: 100%;
			padding-left: 160px;
			line-height: 1.1;
		}

		.notfound .notfound-404 {
			position: absolute;
			left: 0;
			top: 0;
			display: inline-block;
			width: 140px;
			height: 140px;
			background-image:
				url('https://png2.cleanpng.com/sh/2579600f7d2732d4f88591ad4f536048/L0KzQYm3U8E1N6Vtj5H0aYP2gLBuTgNibJ9qiAU2c33sfLbCTfZia5YyfuR4d36wc73wkL1ieqUyet5qY3uwcbBrTgdpcaVqReVqZD3pcbTsTcViaWo5S9VqMXXpQYq8TsQxOmc1UacBMUW1QYG7UsM4QGI3Tqo3cH7q/kisspng-sadness-smiley-face-frown-clip-art-black-and-white-sad-face-5aa943ca1ef195.4026095615210423781268.png');
			background-size: cover;
		}

		.notfound .notfound-404:before {
			content: '';
			position: absolute;
			width: 100%;
			height: 100%;
			-webkit-transform: scale(2.4);
			-ms-transform: scale(2.4);
			transform: scale(2.4);
			border-radius: 50%;
			background-color: #f2f5f8;
			z-index: -1;
		}

		.notfound h1 {
			font-family: 'Nunito', sans-serif;
			font-size: 65px;
			font-weight: 700;
			margin-top: 0px;
			margin-bottom: 10px;
			color: #151723;
			text-transform: uppercase;
		}

		.notfound h2 {
			font-family: 'Nunito', sans-serif;
			font-size: 21px;
			font-weight: 400;
			margin: 0;
			text-transform: uppercase;
			color: #151723;
		}

		.notfound p {
			font-family: 'Nunito', sans-serif;
			color: #999fa5;
			font-weight: 400;
		}

		.notfound a {
			font-family: 'Nunito', sans-serif;
			display: inline-block;
			font-weight: 700;
			border-radius: 40px;
			text-decoration: none;
			color: #388dbc;
		}

		@media only screen and (max-width: 767px) {
			.notfound .notfound-404 {
				width: 110px;
				height: 110px;
			}

			.notfound {
				padding-left: 15px;
				padding-right: 15px;
				padding-top: 110px;
			}
		}
	</style>

</head>

<body>

	<div id="notfound">
		<div id="notfound">
			<div class="notfound">
				<div class="notfound-404"></div>
				<h1>403</h1>
				<h2>Oops! You cannot perform this Operation</h2>
				<p>Your permission to perform this operation is denied. Sorry</p>
				<a href="{% url 'core:homeview' %}">Back to homepage</a>
			</div>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

templates/Error500.html
<!DOCTYPE html>
<html lang="en"> -->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Butopia 500</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<style>
		* {
			-webkit-box-sizing: border-box;
			box-sizing: border-box;
		}

		body {
			padding: 0;
			margin: 0;
		}

		#notfound {
			position: relative;
			height: 100vh;
		}

		#notfound .notfound {
			position: absolute;
			left: 50%;
			top: 50%;
			-webkit-transform: translate(-50%, -50%);
			-ms-transform: translate(-50%, -50%);
			transform: translate(-50%, -50%);
		}

		.notfound {
			max-width: 560px;
			width: 100%;
			padding-left: 160px;
			line-height: 1.1;
		}

		.notfound .notfound-404 {
			position: absolute;
			left: 0;
			top: 0;
			display: inline-block;
			width: 140px;
			height: 140px;
			background-image:
				url('https://png2.cleanpng.com/sh/2579600f7d2732d4f88591ad4f536048/L0KzQYm3U8E1N6Vtj5H0aYP2gLBuTgNibJ9qiAU2c33sfLbCTfZia5YyfuR4d36wc73wkL1ieqUyet5qY3uwcbBrTgdpcaVqReVqZD3pcbTsTcViaWo5S9VqMXXpQYq8TsQxOmc1UacBMUW1QYG7UsM4QGI3Tqo3cH7q/kisspng-sadness-smiley-face-frown-clip-art-black-and-white-sad-face-5aa943ca1ef195.4026095615210423781268.png');
			background-size: cover;
		}

		.notfound .notfound-404:before {
			content: '';
			position: absolute;
			width: 100%;
			height: 100%;
			-webkit-transform: scale(2.4);
			-ms-transform: scale(2.4);
			transform: scale(2.4);
			border-radius: 50%;
			background-color: #f2f5f8;
			z-index: -1;
		}

		.notfound h1 {
			font-family: 'Nunito', sans-serif;
			font-size: 65px;
			font-weight: 700;
			margin-top: 0px;
			margin-bottom: 10px;
			color: #151723;
			text-transform: uppercase;
		}

		.notfound h2 {
			font-family: 'Nunito', sans-serif;
			font-size: 21px;
			font-weight: 400;
			margin: 0;
			text-transform: uppercase;
			color: #151723;
		}

		.notfound p {
			font-family: 'Nunito', sans-serif;
			color: #999fa5;
			font-weight: 400;
		}

		.notfound a {
			font-family: 'Nunito', sans-serif;
			display: inline-block;
			font-weight: 700;
			border-radius: 40px;
			text-decoration: none;
			color: #388dbc;
		}

		@media only screen and (max-width: 767px) {
			.notfound .notfound-404 {
				width: 110px;
				height: 110px;
			}

			.notfound {
				padding-left: 15px;
				padding-right: 15px;
				padding-top: 110px;
			}
		}
	</style>

</head>

<body>

	<div id="notfound">
		<div id="notfound">
			<div class="notfound">
				<div class="notfound-404"></div>
				<h1>500</h1>
				<h2>Oops! Internal Error Occured in the Server</h2>
				<p>An Operation has caused a sever error. The administrators have been notified</p>
				<a href="{% url 'core:homeview' %}">Back to homepage</a>
			</div>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <div class="pt-4">
        <a class="btn btn-outline-white" href="{% url 'core:download' %}" role="button">Download Past Question
            <i class="fas fa-download ml-2"></i>
        </a>
        <a class="btn btn-outline-white" href="{% url 'core:paymentview' %}" role="button">Purchase Full
            License
            <i class="fas fa-graduation-cap ml-2"></i>
        </a>
    </div>


    <hr class="my-4" />

    <div class="pb-4">
        <a href="https://www.facebook.com/maximusjshokes" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>

        <a href="https://twitter.com/showkhunbi" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>

        <a href="https://gsffunaab.com" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>
    </div>

    <div class="footer-copyright py-3">
        © 2020 Copyright:
        <a href="#" target="_blank">
            Johnson Cooper Technologies
        </a>
    </div>
</footer>

templates/form.html
{% extends 'base.html' %} {% block head_style %}
<style type="text/css">
  html,
  body,
  header,
  .view {
    height: 100%;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .view {
      height: 1000px;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .view {
      height: 650px;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {
    .navbar:not(.top-nav-collapse) {
      background: #1c2331 !important;
    }
  }
</style>
{% endblock head_style %} {% block content %}

<!-- Full Page Intro -->
<div class="view full-page-intro" style="
    background-image: url('https://mdbootstrap.com/img/Photos/Others/images/78.jpg');
    background-repeat: no-repeat;
    background-size: cover;
  ">
  <!-- Mask & flexbox options-->
  <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
    <!-- Content -->
    <div class="container mt-5 pt-2">
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 mb-4 white-text text-center text-md-left">
          <h1 class="display-5 font-weight-bold">Purchase GSF FUNAAB Post UTME Past Questions and Solutions Manual Full
            License</h1>

          <hr class="hr-light" />

          <p>
            <strong>Price: N1,500 only</strong>
          </p>
          <p>
            <strong>Best Past Question Pack</strong>
          </p>

          <p class="mb-4 d-none d-md-block">
            <strong>The most comprehensive tutorial book which
              is an essential tool for students who aspire to achieve mastery of the subjects
              included and also excellent results in FUNAAB Screening exercise.</strong>
          </p>

          <a target="_blank" href="{% url 'core:download' %}" class="btn btn-indigo btn-lg">Download
            <i class="fas fa-download ml-2"></i>
          </a>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 col-xl-5 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card content-->
            <div class="card-body">
              <!-- Form -->
              <form id="paymentForm">
                <!-- Heading -->
                <h3 class="dark-grey-text text-center">
                  <strong>Payment</strong>
                </h3>
                <hr />

                <div class="md-form">
                  <i class="fas fa-user prefix grey-text"></i>
                  <input type="text" id="first-name" class="form-control" required />
                  <label for="first-name">First name</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-user prefix grey-text"></i>
                  <input type="text" id="last-name" class="form-control" required />
                  <label for="last-name">Last name</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-phone prefix grey-text"></i>
                  <input type="number" id="phone" class="form-control" />
                  <label for="phone">Phone Number</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-envelope prefix grey-text"></i>
                  <input type="email" id="email-address" {% if email %} value="{{email}}" {% endif %}
                    class="form-control" required />
                  <label for="email-address">Your email</label>
                </div>
                <div class="md-form">
                  <i class="fas fa-id-card prefix grey-text"></i>
                  <input {% if referrer %} value="{{referrer}}" disabled {% endif %} type="text" id="referrer"
                    class="form-control" onkeyup="this.value = this.value.toLowerCase();" />
                  <label for="referrer">Referrer</label>
                </div>
                <div class="text-center">
                  <p style="font-size: x-small; margin-bottom: 0; color: grey">On Clicking the button below, you have
                    agreed to pay
                    N1,500</p>
                  <button class="btn btn-indigo" onclick="payWithPaystack()" type="submit">
                    Proceed to Payment
                  </button>
                </div>
              </form>
              <script src="https://js.paystack.co/v1/inline.js"></script>
              <!-- Form -->
            </div>
          </div>
          <!--/.Card-->
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Content -->
  </div>
  <!-- Mask & flexbox options-->
</div>
<!-- Full Page Intro -->

<script>
  const paymentForm = document.getElementById("paymentForm");
  paymentForm.addEventListener("submit", payWithPaystack, false);

  function payWithPaystack(e) {
    e.preventDefault();
    let handler = PaystackPop.setup({
      key: "pk_test_d9907dcdb41dc7ef8283e61f74c15cd89577716f", // Replace with your public key
      email: document.getElementById("email-address").value,
      amount: 1500 * 100,
      ref: "" + Math.floor(Math.random() * 1000000000 +
        1), // generates a pseudo-unique reference. Please replace with a
      //reference you generated. Or remove the line entirely so our API will generate one for you
      // label: "Optional string that replaces customer email"
      metadata: {
        first_name: document.getElementById("first-name").value,
        last_name: document.getElementById("last-name").value,
        phone: document.getElementById("phone").value,
        referrer_id: document.getElementById("referrer").value
      },
      onClose: function () {
        alert("Window closed.");
      },
      callback: function (response) {
        window.location = "{% url 'core:verify'%}?reference=" + response.reference;
        let message = "Payment complete! Reference: " + response.reference;
        alert(message);
      },
    });
    handler.openIframe();
  }
</script>

{% endblock content %}

templates/nav.html
<!-- Navbar -->
<div class="fixed-top" style=" background: none; margin-top: 70px; z-index: 55; position: absolute; width: 100vw">
    {% if messages %} {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger {% else %} alert-{{message.tags}}{% endif %}
          alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
            <span>&times</span>
        </button>
    </div>
    {% endfor %} {% endif %}
</div>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand" id="sidebarCollapse" href="#">
            <i class="fas fa-align-left"></i>
            <strong>B-Utopia</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" id="homeLink">
                    <a class="nav-link" href="{% url 'core:homeview' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item" id="downloadlink">
                    <a class="nav-link" href="{% url 'core:download' %}">Download</a>
                </li>
                <li class="nav-item" id="paymentLink">
                    <a class="nav-link" href="{% url 'core:paymentview' %}">Payment</a>
                </li>
                <li class="nav-item" id="promoterLink">
                    <a class="nav-link" href="{% url 'core:dashboard' %}">Promoters</a>
                </li>
                <li class="nav-item" id="ourServicesLink">
                    <a class="nav-link" href="{% url 'core:portfolio' %}">Our Services</a>
                </li>
                <li class="nav-item" id="contactUsLink">
                    <a class="nav-link" href="{% url 'core:contact' %}">Contact Us</a>
                </li>
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">

                {% if user.is_authenticated %}
                <li class="nav-item mr-2">
                    <a href="{% url 'account_change_password' %}" class="nav-link border border-light rounded">
                        <i class="fas fa-unlock-alt mr-2"></i>Change Password
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_logout' %}" class="nav-link border border-light rounded">
                        <i class="fas fa-sign-out-alt mr-2"></i>Sign Out
                    </a>
                </li>
                {% else %}
                <li class="nav-item mr-2">
                    <a href="{% url 'account_login' %}" class="nav-link border border-light rounded">
                        <i class="fas fa-sign-in-alt mr-2"></i>Sign in
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link border border-light rounded">
                        <i class="fas fa-user-plus mr-2"></i>Sign up
                    </a>
                </li>
                {% endif %}

            </ul>

        </div>

    </div>
</nav>
<!-- Navbar -->

templates/portfolio.html
{% extends 'base.html' %}
{% load static %}


{% block extra_head %}
<style>
    html,
    body,
    header,
    .view {
        height: 100%;
    }

    /* Carousel*/
    .carousel,
    .carousel-item,
    .carousel-item.active {
        height: 100%;
    }

    .carousel-inner {
        height: 100%;
    }

    @media (min-width: 800px) and (max-width: 850px) {
        .navbar:not(.top-nav-collapse) {
            background: #1C2331 !important;
        }
    }
</style>
{% endblock extra_head %}


{% block content %}
<!-- data-ride="carousel" -->
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

        <!--First slide-->
        <div class="carousel-item active">
            <div class="view" style=" background-image: url('{% static 'images/comp.webp' %}'); background-repeat:
                no-repeat; background-size: cover;">

                <!--Video source-->
                <!-- <video class="video-intro" autoplay loop muted>
                    <source src="{% static 'images/comp.webp' %}" type="video/mp4" />
                </video> -->

                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4 display-1">
                            <strong>Web development</strong>
                        </h1>

                        <p class="lead">
                            <strong>Building of Web sites and Applications</strong>
                        </p>

                        <p class="mb-4 d-none d-md-block lead">
                            <strong>We build and upgrade existing websites to a dynamic and responsive web applications
                                to suit your business needs. Contact us to get your website solutions</strong>
                        </p>

                        <a href="{% url 'core:contact' %}" class="btn btn-outline-white btn-lg">Get your website
                            solutions
                            <i class="fas fa-globe-africa ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->

                </div>
                <!-- Mask & flexbox options-->

            </div>
        </div>
        <!--/First slide-->

        <!--Second slide-->
        <div class="carousel-item">
            <div class="view" style=" background-image: url('{% static 'images/coding-man.webp' %}'); background-repeat:
                no-repeat; background-size: cover;">

                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4 display-1">
                            <strong>Software Development</strong>
                        </h1>

                        <p class="lead">
                            <strong>Building of Android and Windows Applications</strong>
                        </p>

                        <p class="mb-4 d-none d-md-block">
                            <strong>We build cross platform software applications
                                to satisfy your business needs. Contact us to get your software solutions</strong>
                        </p>

                        <a href="{% url 'core:contact' %}" class="btn btn-outline-white btn-lg">Get your Software
                            solutions
                            <i class="fas fa-box-open ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->

                </div>
                <!-- Mask & flexbox options-->

            </div>
        </div>
        <!--/Second slide-->

        <!--Third slide-->
        <div class="carousel-item">
            <div class="view" style=" background-image: url('{% static 'images/4474520.webp' %}'); background-repeat:
                no-repeat; background-size: cover;">

                <!--Video source-->
                <!-- <video class="video-intro" autoplay loop muted>
                    <source src="https://mdbootstrap.com/img/video/forest.mp4" type="video/mp4" />
                </video> -->

                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4 display-1">
                            <strong>Programming Lessons</strong>
                        </h1>

                        <p>
                            <strong class="lead">Learn Programming from our Educators</strong>
                        </p>

                        <p class="mb-4 d-none d-md-block lead">
                            <strong>We offer Physical tutorials for beginners and virtual mentorship for advanced
                                learners</strong>
                        </p>

                        <a href="{% url 'core:contact' %}" class="btn btn-outline-white btn-lg">Book a Session
                            <i class="fas fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->

                </div>
                <!-- Mask & flexbox options-->

            </div>
        </div>
        <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container">

        <!--Section: Main info-->
        <section class="mt-5 wow fadeIn">

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{% static 'images/scshot.webp' %}" class="img-fluid z-depth-1-half" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!-- Main heading -->
                    <h3 class="h3 mb-3">General Programming Solutions</h3>
                    <p>We provide you with any type of Programming solutions you require for your business.</p>
                    <p>This may include Data Sourcing and analysis, Automation e.t.c</p>
                    <!-- Main heading -->
                    <hr>
                    <p>
                        Learn More or Get started by contacting Johnson Cooper
                    </p>
                    <!-- CTA -->
                    <a href="{% url 'core:contact' %}" class="btn btn-grey btn-md">Contact
                        <i class="fas fa-download ml-1"></i>
                    </a>

                </div>
                <!--Grid column-->
            </div>
            <hr>
            <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{% static 'images/4474520.webp' %}" class="img-fluid z-depth-1-half" alt="">

                </div>
                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!-- Main heading -->
                    <h3 class="h3 mb-3">Web Development Solutions</h3>
                    <p>We provide you with any type of Web development solutions that satisfies your business.</p>
                    <p>This may include Web Applications, Blogging websites e.t.c </p>
                    <!-- Main heading -->
                    <hr>
                    <p>
                        Learn More or Get started by contacting Johnson Cooper
                    </p>
                    <!-- CTA -->
                    <a href="{% url 'core:contact' %}" class="btn btn-grey btn-md">Contact
                        <i class="fas fa-download ml-1"></i>
                    </a>

                </div>
                <!--Grid column-->
            </div>
            <hr>
            <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{% static 'images/coding-man.webp' %}" class="img-fluid z-depth-1-half" alt="">

                </div>
                <div class="col-md-6 mb-4">

                    <!-- Main heading -->
                    <h3 class="h3 mb-3">Software Development Solutions</h3>
                    <p>We provide you with any type of Software development solutions that satisfies your business.
                    </p>
                    <p>This may include Android, P.C softwares</p>
                    <!-- Main heading -->
                    <hr>
                    <p>
                        Learn More or Get started by contacting Johnson Cooper
                    </p>
                    <!-- CTA -->
                    <a href="{% url 'core:contact' %}" class="btn btn-grey btn-md">Contact
                        <i class="fas fa-download ml-1"></i>
                    </a>

                </div>
                <!--Grid column-->
            </div>

            <!--Grid row-->

        </section>
        <!--Section: Main info-->

    </div>
</main>
<!--Main layout-->
{% endblock content %}